/**
 * ============================================================
 * js/articles-data.js — Base de donnees partagee des articles
 * ============================================================
 */

const ARTICLES_DB = [
    {
        id: 1,
        nom: 'Veste en cuir vintage',
        cat: 'Vetements Luxe',
        prix: 180,
        prixAffiche: '180 EUR',
        mode: 'negotiation',
        type: 'haute_gamme',
        vendeur: 'Marc Martin',
        vendeurPseudo: 'Marc M.',
        date: '08/03/2026',
        description: "Belle veste en cuir veritable, annees 80, tres bon etat general. Couleur marron fonce, doublure interieure. Taille M/L.",
        defauts: "Legeres marques d'usure sur les coudes, visible de pres.",
        img: 'images/vestecuir.jpg',
        couleurFond: ['#2d1b00','#8b4513'],
    },
    {
        id: 2,
        nom: 'MacBook Pro 2021',
        cat: 'Electronique',
        prix: 1200,
        prixAffiche: '1 200 EUR',
        mode: 'immediat',
        type: 'haute_gamme',
        vendeur: 'Sophie Leclerc',
        vendeurPseudo: 'Sophie L.',
        date: '07/03/2026',
        description: "MacBook Pro 16 pouces, puce M1 Pro, 16 Go RAM, 512 Go SSD. Tres bon etat, batterie en bonne sante. Vendu avec chargeur original.",
        defauts: "Legere rayure sur le coin inferieur gauche du boitier.",
        img: 'images/macbook.jpg',
        couleurFond: ['#1a1a2e','#16213e'],
    },
    {
        id: 3,
        nom: 'Chaise longue LC4',
        cat: 'Mobilier Antique',
        prix: 95,
        prixAffiche: '95 EUR',
        mode: 'immediat',
        type: 'regulier',
        vendeur: 'Thomas Bernard',
        vendeurPseudo: 'Thomas B.',
        date: '06/03/2026',
        description: "Chaise longue style LC4 Le Corbusier, structure metallique chromee, cuir noir. Design iconique, tres bon etat general.",
        defauts: "Aucun defaut apparent.",
        img: 'images/chaise.jpg',
        couleurFond: ['#2e2e1a','#7d6e2e'],
    },
    {
        id: 4,
        nom: 'Collection Harry Potter integrale',
        cat: 'Art et Collections',
        prix: 45,
        prixAffiche: '45 EUR',
        mode: 'negotiation',
        type: 'rare',
        vendeur: 'Marc Martin',
        vendeurPseudo: 'Marc M.',
        date: '05/03/2026',
        description: "Integrale Harry Potter + Les Animaux Fantastiques — 11 films en Blu-ray + Puzzle 3D Poudlard La Tour de l'Horloge 420 pieces (Wrebbit3D). Coffret collector.",
        defauts: "Boite en tres bon etat, puzzle non ouvert.",
        img: 'images/colection_haryypotter.jpg',
        couleurFond: ['#1a2e1a','#2e7d32'],
    },
    {
        id: 5,
        nom: 'Sac Longchamp Le Pliage',
        cat: 'Accessoires Mode',
        prix: 120,
        prixAffiche: '120 EUR',
        mode: 'immediat',
        type: 'haute_gamme',
        vendeur: 'Sophie Leclerc',
        vendeurPseudo: 'Sophie L.',
        date: '04/03/2026',
        description: "Sac Longchamp Le Pliage, coloris bleu marine, anses et rabat en cuir cognac. Utilise quelques fois, excellent etat. Fermeture eclair fonctionnelle.",
        defauts: "Aucun defaut notable.",
        img: 'images/sac.jpg',
        couleurFond: ['#2e1a2a','#8c3d7a'],
    },
    {
        id: 6,
        nom: 'Calculatrice solaire Addex',
        cat: 'Materiel Scolaire',
        prix: 25,
        prixAffiche: '25 EUR',
        mode: 'immediat',
        type: 'regulier',
        vendeur: 'Thomas Bernard',
        vendeurPseudo: 'Thomas B.',
        date: '03/03/2026',
        description: "Calculatrice de bureau Addex a energie solaire, grand ecran inclinable, touches rondes ergonomiques. Toutes les fonctions operationnelles.",
        defauts: "Traces d'utilisation legeres sur le boitier.",
        img: 'images/calculatrice.jpg',
        couleurFond: ['#1a1a2e','#3d3d8c'],
    },
    {
        id: 7,
        nom: 'Bracelet argent artisanal',
        cat: 'Bijoux et Montres',
        prix: 55,
        prixAffiche: '55 EUR',
        mode: 'negotiation',
        type: 'rare',
        vendeur: 'Marc Martin',
        vendeurPseudo: 'Marc M.',
        date: '02/03/2026',
        description: "Bracelet chaine en argent 925, maille figaro, presente dans son ecrin rouge. Fermeture a mousqueton. Piece elegante et classique.",
        defauts: "Legere oxydation sur une zone, facilement nettoyable.",
        img: 'images/barcelet.jpg',
        couleurFond: ['#1a2e2e','#0e8c8c'],
    },
    {
        id: 8,
        nom: 'Guitare acoustique Ibanez',
        cat: 'Art et Collections',
        prix: 200,
        prixAffiche: '200 EUR',
        mode: 'enchere',
        type: 'haute_gamme',
        vendeur: 'Sophie Leclerc',
        vendeurPseudo: 'Sophie L.',
        date: '01/03/2026',
        description: "Guitare acoustique 12 cordes Ibanez, corps noir brillant, pan coupe, livree avec son etui rigide. Son riche et chaleureux.",
        defauts: "Petite egratignure sur la caisse, inaudible au jeu.",
        img: 'images/guitare.jpg',
        couleurFond: ['#2d1b69','#7c3aed'],
    },
    {
        id: 9,
        nom: 'Parfum Chanel N5',
        cat: 'Accessoires Mode',
        prix: 90,
        prixAffiche: '90 EUR',
        mode: 'immediat',
        type: 'haute_gamme',
        vendeur: 'Thomas Bernard',
        vendeurPseudo: 'Thomas B.',
        date: '28/02/2026',
        description: "Eau de parfum Chanel N5, 50ml, flacon entame avec sa boite d'origine. Authentique, achete en boutique officielle.",
        defauts: "Flacon entame, environ 35ml restants.",
        img: 'images/parfum.jpg',
        couleurFond: ['#1a1a1a','#4a4a4a'],
    },
    {
        id: 10,
        nom: 'Velo de ville',
        cat: 'Materiel Scolaire',
        prix: 350,
        prixAffiche: '350 EUR',
        mode: 'negotiation',
        type: 'regulier',
        vendeur: 'Marc Martin',
        vendeurPseudo: 'Marc M.',
        date: '27/02/2026',
        description: "Velo de ville aluminium, vitesses Shimano, garde-boues et porte-bagages inclus. Taille M, convient pour 1m65-1m80. Ideal campus.",
        defauts: "Pneu arriere legerement use, freins a regler.",
        img: 'images/velo.jpg',
        couleurFond: ['#1a2e1a','#4a7a4a'],
    },
    {
        id: 11,
        nom: 'Tableau photo panoramique',
        cat: 'Art et Collections',
        prix: 500,
        prixAffiche: '500 EUR',
        mode: 'enchere',
        type: 'rare',
        vendeur: 'Sophie Leclerc',
        vendeurPseudo: 'Sophie L.',
        date: '26/02/2026',
        description: "Tableau photo panoramique sur verre, motif pissenlit bleu avec gouttes d'eau, format XXL. Impression haute definition, rendu tres moderne.",
        defauts: "Cadre legerement abime sur un coin.",
        img: 'images/tabelau.jpg',
        couleurFond: ['#0d2137','#1565a8'],
    },
    {
        id: 12,
        nom: 'Appareil photo argentique Pentax',
        cat: 'Electronique',
        prix: 145,
        prixAffiche: '145 EUR',
        mode: 'enchere',
        type: 'rare',
        vendeur: 'Thomas Bernard',
        vendeurPseudo: 'Thomas B.',
        date: '25/02/2026',
        description: "Pentax P30 argentique avec objectif zoom et flash Pentax. Obturateur verifie, fonctionne parfaitement. Vendu avec pellicule. Ideal pour la photo argentique.",
        defauts: "Legere usure cosmetique sur le boitier.",
        img: 'images/appreilphoto.jpg',
        couleurFond: ['#4a1a00','#e65100'],
    },
];

function getArticleById(id) {
    return ARTICLES_DB.find(a => a.id === parseInt(id)) || null;
}

const MODE_LABELS = {
    immediat:    'Achat immediat',
    negotiation: 'Negociation',
    enchere:     'Enchere',
};

const TYPE_LABELS = {
    haute_gamme: 'Luxe',
    rare:        'Rare',
    regulier:    'Regulier',
};

const CTA_LABELS = {
    immediat:    'Acheter',
    negotiation: 'Negocier',
    enchere:     'Encherir',
};
